---
version: 2

references:
  steps: &steps
    - checkout

    - type: cache-restore
      key: prometheus-client-tracer-bundler-{{ checksum "prometheus-client-tracer.gemspec" }}

    - run: gem install bundler -v 2.0.1
    - run: bundle install --path vendor/bundle

    - type: cache-save
      key: prometheus-client-tracer-bundler-{{ checksum "prometheus-client-tracer.gemspec" }}
      paths:
        - vendor/bundle

    - run: bundle exec rubocop
    - run: bundle exec rspec

jobs:
  build-ruby24:
    docker:
      - image: ruby:2.4
    steps: *steps
  build-ruby25:
    docker:
      - image: ruby:2.5
    steps: *steps
  build-ruby26:
    docker:
      - image: ruby:2.6
    steps: *steps

workflows:
  version: 2
  tests:
    jobs:
      - build-ruby24
      - build-ruby25
      - build-ruby26
